### ISSUE TITLE
Total steps by day

### ISSUE THREAD

**Issue by bckthomas** [AyraHikari/HealthConnect_to_HomeAssistant#3]
Hi
Thanks for this extension !

I would like to add a apexCharts with the number of steps by day.
It seems the extension push the last step section of the day

![Image](https://github.com/user-attachments/assets/eb310a7b-8bd6-4907-a158-bda647699810)

Can you push the total per day ? Or is it possible to add all the sections to get the total amount by day ?

![Image](https://github.com/user-attachments/assets/943a5036-ffde-40d8-b43a-a296858f1e88)

Thanks

**Comment by Ken7382** [comment]
I created this but it's not perfect.. you're welcome to give it a shot:

```
type: custom:apexcharts-card
header:
  title: Steps
  show: true
graph_span: 6d
span:
  start: day
  offset: "-6d"
apex_config:
  chart:
    height: 300px
  stroke:
    curve: smooth
    width: 2
series:
  - entity: sensor.health_sensor
    name: Steps
    color: "#2358ba"
    type: column
    extend_to: now
    float_precision: 0
    show:
      in_header: true
    data_generator: |
      const steps = entity.attributes.steps;
      return Object.entries(steps)
      .map(([date, values]) => [date, values.count])
      .sort((a, b) => new Date(a[0]) - new Date(b[0]));
yaxis:
  - min: 0
    max: 20000
    decimals: 0
```

<img width="529" height="373" alt="Image" src="https://github.com/user-attachments/assets/2c072cae-0605-4956-83b6-e17c9fa88e58" />

This should at least get you going and show steps..
